### ISSUE TITLE
Faz lá o primeiro commit pah

### ISSUE THREAD

**Issue by daviddias** [require-lx/marmitajs#1]
Também quero contribuir! @joaojeronimo  :P

**Comment by joaojeronimo** [comment]
peraí ainda não consegui arranjar tempo para meter lá coisas lol afinal o código do @darkbls é mais complicado do que eu imaginava...

**Comment by joaojeronimo** [comment]
minto, por acaso é muito simples, já vejo isso...

**Comment by lnaia** [comment]
Lies lies :)
A ideia é simples:
array com ementa
coisas para iterar sobre a ementa e separar por categorias (base, ingrediente primary e secundario)
post to target URL

a coisa do estar confuso, just ignore :D

**Comment by daviddias** [comment]
Habemos logo (vá temporário, foi feito ontem a noite xD)
![marmita.js](https://github.com/require-lx/marmitajs/blob/master/assets/marmita-termopratica-revestida-em-aco-inox-3-unidades_MLB-F-183935740_5957.png?raw=true)

Já adicionei o menu de saladas e o random meal thing em .js

**Comment by joaojeronimo** [comment]
que logo brutal!

**Comment by lnaia** [comment]
Complemente :o
